-- One-use credential handoff links.
-- Target: VAP App prod (jjckotsrhuxxftwmdlwc)
--
-- Purpose: let an outside party (a CRM vendor, a franchisor support desk, a
-- client's IT contact) hand us API credentials without emailing them and
-- without giving them an account anywhere. We create a row with a random
-- token, send them handoff.html?t=<token>, they fill it in once, and the link
-- is dead.
--
-- DELIBERATELY ISOLATED, like franchisor_intake_submissions (015): no foreign
-- keys, no triggers, no webhooks, no provisioning path. In particular it is
-- NOT location_intake_submissions, whose AFTER INSERT OR UPDATE trigger posts
-- to the #client-onboarding Slack channel -- credentials must not generate a
-- Slack message.
--
-- RLS is enabled with NO anon or authenticated policies and no grants to those
-- roles, so the table is unreachable from the browser in either direction. The
-- page talks only to the `credential-handoff` edge function, which holds the
-- service role key. That is what makes single-use enforceable: an anon-writable
-- table can always be re-written by whoever holds the link.

create table if not exists public.credential_handoffs (
  id uuid primary key default gen_random_uuid(),

  -- Random URL token. Generated by whoever creates the request; treat as a
  -- bearer secret (anyone holding it can submit once).
  token text not null unique,

  -- Shown on the page so the recipient can tell what this link is for.
  label text not null,
  intro text,

  -- What to collect: [{ key, label, type, group, help, required }]
  -- type: text | password | email | textarea | checkbox
  -- group: optional heading used to bucket fields (e.g. one per studio)
  fields jsonb not null,

  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '14 days'),

  -- Set atomically on the single accepted submission. Non-null = link is spent.
  submitted_at timestamptz,
  payload jsonb,

  -- Coarse submission provenance for audit. No IP is stored: it is not needed
  -- to verify a handoff and would outlive its usefulness in a credentials table.
  submitted_user_agent text,

  -- Internal note (who we sent it to, which thread).
  notes text
);

create index if not exists credential_handoffs_token_idx
  on public.credential_handoffs (token);

alter table public.credential_handoffs enable row level security;

-- service_role only, on purpose. Do not add anon/authenticated grants: the
-- browser reaches this table exclusively through the edge function.
grant all on public.credential_handoffs to service_role;

revoke all on public.credential_handoffs from anon;
revoke all on public.credential_handoffs from authenticated;

comment on table public.credential_handoffs is
  'One-use links for collecting credentials from outside parties. Written only by the credential-handoff edge function (service role). Read the payload, hand the credentials to their permanent home, then delete the row.';
